const foods = [
  `Don't Mind`,
  "Lasagne",
  "Cremeeschnitte",
  "Laksa",
  "Gyoza",
  "Tempura",
  "Falafel",
  "Tortas",
  "Spring rolls",
  "Miso soup",
  "Berbecue",
  "Baklava",
  "Crème brulee",
  "Kare",
  "Souffle",
  "Pizza",
  "Pizza Margherita",
  "Panna cotta",
  "Guacamole",
  "Chutney",
  "Kimchi",
  "Tofu",
  "Borscht",
  "Gaufre",
  "Makizushi",
  "Moussaaka",
  "Pavlova",
  "Churros",
  "Quesadilla",
  "Tamal",
  "Bulgogi",
  "Bibimbap",
  "Parmigiano Reggiano",
  "Baguette",
  "Pretzel",
  "Cellophane Noodles",
  "Thai curry",
  "Sarma",
  "Satay",
  "Chocolate chip cookie",
  "Fajitas",
  "Naan",
  "Tonkatsu",
  "Nachos",
  "Udon",
  "Pommes frites",
  "Shabu-shabu",
  "Pasta",
  "Chips",
  "Fish &chips",
  "French fries",
  "Ice cream ",
  "Bread",
  "Fried rice",
  "Pancakes",
  "Burger",
  "Pumpkin pie",
  "Chicken pot pie",
  "Banana",
  "Apple pie",
  "Bagel",
  "Muffins",
  "Alfredo sauce",
  "Peanuts",
  "Ice cream cake",
  "Cheese cake",
  "Cheese",
  "Banana bread",
  "Potato chips",
  "Cheetos",
  "Doritos",
  "Tacos",
  "Burritos",
  "Chimichanga",
  "Enchilada",
  "Salsa",
  "Marinara sauce",
  "Broccoli",
  "Chocolate covered strawberried",
  "Kiwi",
  "Tomato",
  "Salad",
  "Steak",
  "Chicken tenders",
  "Chicken and chips",
  "Grilled chicken",
  "Ribs",
  "Biscuits and gravy",
  "Hot dogs",
  "Eggs",
  "Fried chicken",
  "Roasted chicken",
  "Wings and chips",
  "Mashed potato",
  "Stuffing",
  "Brownies",
  "Cookies",
  "Submarine sandwich",
  "Donuts",
  "Turkey",
  "Cranberry",
  "Green beans",
  "Mac and cheese",
  "Soup",
  "Lamb chops",
  "Sushi",
  "Teriyaki",
  "Popcorn",
  "Shrimp",
  "King prawn",
  "Prawn",
  "Lasagna ",
  "Ravioli",
  "Pudding",
  "Meatballs",
  "Gyro sandwich",
  "Onion rings",
  "Chocolate cake",
  "Tater tots",
  "French toast ",
  "Baked potato",
  "Olive garden breadsticks",
  "Crepes",
  "Chicken nuggets",
  "Croissant",
  "Apple sauce",
  "Green bean casserole with fried chicken",
  "Sweet potatoes ",
  "Potato",
  "Cantaloupe",
  "Orange",
  "Strawberries",
  "Peaches",
  "Honeydew",
  "Ginger brea",
  "Mango",
  "Raspberries",
  "Blueberries",
  "Chicken curry",
  "Meat curry, lamb",
  "Meat curry, beef",
  "Corn",
  "Tamale",
  "Fried zucchini blossoms",
  "Calzone",
  "Quiche",
  "Borek",
  "Enchiladas",
  "Onigiri",
  "Fudge",
  "Albanian",
  "Argentine",
  "Andhra",
  "Anglo-Indian",
  "Arab",
  "Armenian",
  "Assyrian",
  "Awadhi",
  "Azerbaijani",
  "Balochi",
  "Belarusian",
  "Bangladeshi",
  "Bengali",
  "Berber",
  "Brazilian",
  "Buddhist",
  "Bulgarian",
  "Cajun",
  "Cantonese",
  "Caribbean",
  "Chechen",
  "Chinese cuisine",
  "Chinese Islamic",
  "Circassian",
  "Crimean Tatar",
  "Cypriot",
  "Danish",
  "English",
  "Estonian",
  "French",
  "Filipino",
  "Georgian",
  "German",
  "Goan",
  "Goan Catholic",
  "Greek",
  "Gujarati",
  "Hyderabad",
  "Indian cuisine",
  "Indian Chinese",
  "Indian Singaporean cuisine",
  "Indonesian",
  "Inuit",
  "Irish",
  "Italian-American",
  "Italian cuisine",
  "Jamaican",
  "Japanese",
  "Jewish",
  "Karnataka",
  "Kazakh",
  "Keralite",
  "Korean",
  "Kurdish",
  "Laotian",
  "Lebanese",
  "Latvian",
  "Lithuanian",
  "Louisiana Creole",
  "Maharashtrian",
  "Mangalorean",
  "Malay",
  "Malaysian Chinese cuisine",
  "Malaysian Indian cuisine",
  "Mediterranean cuisine",
  "Mexican",
  "Mordovian",
  "Mughal",
  "Native American",
  "Nepalese",
  "New Mexican",
  "Odia",
  "Parsi",
  "Pashtun",
  "Polish",
  "Pennsylvania Dutch",
  "Pakistani",
  "Peranakan",
  "Persian",
  "Peruvian",
  "Portuguese",
  "Punjabi",
  "Rajasthani",
  "Romanian",
  "Russian",
  "Sami",
  "Serbian",
  "Sindhi",
  "Slovak",
  "Slovenian",
  "Somali",
  "South Indian",
  "Soviet",
  "Spanish",
  "Sri Lankan",
  "Taiwanese",
  "Tatar",
  "Thai",
  "Turkish",
  "Tamil",
  "Udupi",
  "Ukrainian",
  "Vietnamese",
  "Yamal",
  "Zambian",
  "Zanzibari",
];

export default foods;
