const hobbies = [
'  Other',
'  3D printing',
'  ATV Riding',
'  Acrobatics',
'  Acting',
'  Action Figure Collecting',
'  Aircraft Spotting',
'  Airsoft',
'  Amateur astronomy',
'  Amateur radio',
'  American Football',
'  American football',
'  Angling',
'  Animal Rearing',
'  Animal husbandry',
'  Animal keeping',
'  Animating',
'  Animation',
'  Antiquing',
'  Antiquities',
'  Aquascaping',
'  Archery',
'  Archery',
'  Architecture',
'  Art collecting',
'  Arts & Crafts',
'  Association football',
'  Astronomy',
'  Athletics',
'  Audiophile',
'  Australian rules football',
'  Auto audiophilia',
'  Auto racing',
'  Axe throwing',
'  Backgammon',
'  Backyard chicken rearing',
'  Badminton',
'  Badminton',
'  Baking',
'  Barbecuing',
'  Baseball',
'  Baseball',
'  Basketball',
'  Bath bombs',
'  Baton twirling',
'  Beach volleyball',
'  Beading',
'  Beauty pageants',
'  Bicycling',
'  Billiards',
'  Birdwatching',
'  Blogging',
'  Board games',
'  Board/tabletop games',
'  Boardgames',
'  Boating',
'  Book collecting',
'  Book discussion clubs',
'  Book restoration',
'  Bow making',
'  Bowling',
'  Bowls',
'  Boxing',
'  Brainy hobbies',
'  Brazilian jiu-jitsu',
'  Breadmaking',
'  Breakdancing',
'  Bridge',
'  Building anything',
'  Building electronics',
'  Bullet journaling',
'  Bus spotting',
'  Button collecting',
'  Cabaret',
'  Cake decorating',
'  Cake making',
'  Calligraphy',
'  Camping',
'  Candle making',
'  Canning and food preservation',
'  Canoeing',
'  Car boot sale',
'  Car fixing & building',
'  Car racing',
'  Caram board game',
'  Card games',
'  Cartophily (card collecting)',
'Charity fundraising',
'Checkers (draughts)',
'Cheerleading',
'Cheesemaking',
'Chess',
'Church volunteering',
'Circuit crafts',
'Cleaning',
'Climbing',
'Clothes making',
'Coding',
'Coffee roasting',
'Coin collecting',
'Color guard',
'Coloring',
'Colouring',
'Comic book collecting',
'Compelling playlists',
'Computer programming',
'Confectionery',
'Cooking',
'Cosplaying',
'Couponing',
'Craft',
'Create online courses',
'Creative writing',
'Cribbage',
'Cricket',
'Cricket',
'Crochet',
'Crocheting',
'Croquet',
'Cross-stitch',
'Crossoword/Sudoku',
'Crossword puzzles',
'Cryptography',
'Cue sports',
'Curling',
'Curling',
'Cycling',
'Cycling',
'DIY',
'DJing',
'Dance',
'Dancing',
'Darts',
'Darts',
'Debates',
'Debating',
'Decorating',
'Deltiology (postcard collecting)',
'Die-cast toy',
'Digital arts',
'Disability Sport',
'Disc golf',
'Distro Hopping',
'Diving',
'Diving',
'Do it yourself',
'Dog sport',
'Doll making',
'Dolls',
'Domestic violence shelter volunteering',
'Dominoes',
'Drama',
'Drawing',
'Drink mixing',
'Driving',
'Eating different cuisines',
'Electronic Sport',
'Electronic games',
'Electronics',
'Element collecting',
'Embroidery',
'Ephemera collecting',
'Equestrian',
'Equestrianism',
'Esports',
'Exhibition drill',
'Experimenting',
'Exploration',
'Exploring',
'Fabric paining',
'Faith centre volunteering',
'Fantasy sports',
'Fashion',
'Fashion design',
'Fencing',
'Fencing',
'Field hockey',
'Figure skating',
'Fishing',
'Fishkeeping',
'Fitness & training',
'Fitness classes',
'Flipping furniture',
'Flipping items',
'Flower arranging',
'Flower collecting and pressing',
'Fly tying',
'Flying',
'Following racing tournaments',
'Food tasting',
'Footbag',
'Football',
'Football',
'Foreign language learning',
'Formula 1',
'Fossil hunting',
'Foster care home volunteering',
'Freelancing',
'Frisbee',
'Fruit carving',
'Furniture building',
'Fusilately (phonecard collecting)',
'Gaelic Games',
'Gaming',
'Gaming (tabletop games and role-playing games)',
'Gardening',
'Genealogy',
'Geocaching',
'Gingerbread house making',
'Glamping',
'Glassblowing',
'Go-karting',
'Golf',
'Golfing',
'Gongoozling',
'Graphic design',
'Grilling',
'Gunsmithing',
'Gymnastics',
'Gymnastics',
'Hacking',
'Handball',
'Handball',
'Hanging out with friends',
'  Herp keeping',
'Herping',
'Hiking/Backpacking',
'Hockey',
'Home improvement',
'Homebrewing',
'Horse Racing',
'Horseback riding',
'Horseshoes',
'Hospital volunteering',
'Houseplant care',
'Hula hooping',
'Hunting',
'Hydroponics',
'Ice Hockey',
'Ice hockey',
'Ice skating',
'Iceboat racing',
'Insect collecting',
'Instagram',
'Interior design',
'Jewellery making',
'Jigsaw puzzles',
'Jogging',
'Journaling',
'Judo',
'Judo',
'Juggling',
'Jujitsu',
'Jukskei',
'Jumble sale',
'Kabaddi',
'Karaoke',
'Karate',
'Kart racing',
'Kendama',
'Kickboxing',
'Knife collecting',
'Knife making',
'Knife throwing',
'Knitting',
'Knot tying',
'Knowledge/word games',
'Kombucha brewing',
'Lace making',
'Lacrosse',
'Landscaping',
'Lapidary',
'Laser tag',
'Leaf Pressing',
'Learning',
'Learning new languages',
'Learning new skills',
'Leather crafting',
'Lego building',
'Library volunteering',
'List of hobbies and interests',
'Listening to music',
'Listening to nasheeds',
'Listening to podcasts',
'Lock picking',
'Long-distance running',
'Longboarding',
'Machining',
'Macrame',
'Magic',
'Magnet fishing',
'Mahjong',
'Makeup',
'Marbles',
'Marching band',
'Martial arts',
'Mazes (indoor/outdoor)',
'Meals on wheels volunteering',
'Meditation',
'Mentoring',
'Metal detecting',
'Metalworking',
'Meteorology',
'Microscopy',
'Minature structure crafting',
'Mineral collecting',
'Mixed Martial Arts',
'Model United Nations',
'Model aircraft',
'Model building',
'Model engineering',
'Model racing',
'Modelling',
'Moderating an online group',
'Modern Pentathlon',
'Mosaics',
'Motorsport',
'Movie and movie memorabilia collecting',
'Music lessons',
'Nail art',
'Needlepoint',
'Netball',
'Netball',
'Netball volleyball',
'Nursing home volunteering',
'Oil painting',
'Olympic Sports',
'Orienteering',
'Origami',
'Outdoors',
'Paintballing',
'Painting',
'Perfume',
'Pet adoption & fostering',
'Philately',
'Phillumeny',
'Photography',
'Pilates',
'Pin (lapel)',
'Pintrest',
'Playing a musical instrument',
'Playing an Instrument',
'Playing musical instruments',
'Podcasting',
'Poetry',
'Poi',
'Poker',
'Pool',
'Pottery',
'Powerboat racing',
'Powerlifting',
'Practical jokes',
'Pressed flower craft',
'Printing',
'Programming',
'Proofreading',
'Public Speaking',
'Putting together models',
'Puzzles',
'Quidditch',
'Quilling',
'Quilting',
'Quizzes',
'Race walking',
'Racquetball',
'Radio-controlled car racing',
'Rail transport modelling',
'Rapping',
'Record collecting',
'Refinishing',
'Reiki',
'Research',
'Researching',
'Road trips',
'Robot combat',
'Rock balancing',
'Rock tumbling',
'Role-playing games',
'Roller derby',
'Rowing',
"Rubik's Cube",
'Rugby League',
'Rugby Union',
'Rugby league football',
'Running',
'Sailing',
'Sand Art',
'Satellite watching',
'School volunteering',
'Science Experiments',
'Scrapbooking',
'Sculling or rowing',
'Sculpting',
'Scutelliphily',
'Sea glass collecting',
'Seashell collecting',
'Selling a product from home',
'Senior citizens centre volunteering',
'Series/Movie watching',
'Sewing',
'Shoemaking',
'Shoes',
'Shogi',
'Shooting',
'Shooting sport',
'Shopping',
'Shortwave listening',
'Singing',
'Skateboarding',
'Sketching',
'Skiing',
'Sled dog racing',
'Slot car racing',
'Snapchat',
'Snooker',
'Snorkelling',
'Soap making',
'Soapmaking',
'Social media',
'Sodoku',
'Softball',
'Song writing',
'Speed skating',
'Speedcubing',
'Sport stacking',
'Sports memorabilia',
'Squash',
'Squash',
'Stamp collecting',
'Stand-up comedy',
'Stone collecting',
'Story telling',
'Story writing',
'Stuffed toy collecting',
'Supporting football clubs',
'Supporting football teams',
'Surfing',
'Swimming',
'Swimming',
'Swimming',
'Table Tennis',
'Table football',
'Table tennis',
'Taekwondo',
'Tarot',
'Taxidermy',
'Tea bag collecting',
'Tennis',
'Tennis',
'Tennis polo',
'Tether car',
'Thrifting',
'Ticket collecting',
'Tiktok',
'Tour skating',
'Toys',
'Trainspotting',
'Trapshooting',
'Travelling',
'Triathlon',
'Triathlon',
'Tutoring',
'Tweeting',
'Twitch channel',
'Ultimate frisbee',
'Video Games',
'Video editing',
'Video game collecting',
'Video game developing',
'Video gaming',
'Videophilia',
'Vintage cars',
'Vintage clothing',
'Vinyl Records',
'Virtual assistant',
'Vlogging',
'Volleyball',
'Volleyball',
'Volunteering',
'Walking',
'Watching movies',
'Watching television',
'Water aerobics',
'Water polo',
'Watercolour painting',
'Waxing',
'Wealth making',
'Weaving',
'Weight training',
'Weightlifting',
'Weightlifting',
'Welding',
'Whale watching',
'Whittling',
'Wikipedia editing',
'Wild camping',
'Winemaking',
'Winter Sports',
'Wood burning',
'Wood carving',
'Woodworking',
'Word searches',
'Working out',
'Worldbuilding',
'Wrestling',
'Wrestling',
'Write a book or ebook',
'Writing',
'Yo-yoing',
'Yoga',
'Youtube channel',
'Zumba',
];

export default hobbies;
