name: CD

on:
  push:
      branches: [ main ]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
              -   uses: actions/checkout@v2
              -   name: Deploy to production
                  uses: appleboy/ssh-action@master
                  with:
                      username: ${{ secrets.username }}
                      host: ${{ secrets.host }}
                      password: ${{ secrets.SSH_PASSWORD }}
                      passphrase: ${{ secrets.pass }}
                      script: ${{ secrets.command }}

